name = "sso-broker"
main = "worker.js"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]
account_id = "8f44c3760fd7f6aa617b39467f513b48"
workers_dev = true

# Environment variables
[vars]
# Environment setting (development/production)
ENVIRONMENT = "development"
# Client IDs (public identifiers - safe to hardcode)
APPLE_CLIENT_ID = "broker.sso"
GOOGLE_CLIENT_ID = "576821248153-hqdde1vhla24i1127rcskhlqjfvq8lou.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Iv23libbe6N7MUtBWv6C"

# Apple OAuth Configuration (public identifiers - safe to hardcode)
APPLE_TEAM_ID = "G4QE2DESTS"
APPLE_KEY_ID = "6XJMPKAUHX"

# Secrets (set via: wrangler secret put SECRET_NAME)
# APPLE_CLIENT_SECRET (contains the private key for JWT signing)
# GOOGLE_CLIENT_SECRET
# GITHUB_CLIENT_SECRET
# MASTER_SECRET (for signing client credentials)

# SAML Configuration (set via: wrangler secret put SECRET_NAME)
# SAML_CERT (shared certificate for all SAML providers)
# SAML_PRIVATE_KEY (shared private key for all SAML providers)
